### ISSUE TITLE
Does this addon version match the non-addon version?

### ISSUE THREAD

**Issue by salmoaz** [basnijholt/home-assistant-streamdeck-yaml-addon#136]
Does this addon (home-assistant-streamdeck-yaml-addon) match the content in (home-assistant-streamdeck-yaml)? 

At the time of writing this, my HA and this (home-assistant-streamdeck-yaml-addon) show version 2024.6 3.  On the (home-assistant-streamdeck-yaml) page I see the current version is 2024.7.5. Are these equivalent? I am setting up a stream deck plus and it looks like some of the most recent udpates included additional support.

My vocabulary in this area is not the greatest, hopefully the intent is clear

**Comment by basnijholt** [comment]
This is the add-on for HA supervised. I just updated this repo to the latest version.

**Comment by salmoaz** [comment]
> This is the add-on for HA supervised. I just updated this repo to the latest version.

Incredible, thanks for taking a look at this so quickly! Very much appreciate your work on this
