### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by tannerwastaken** [basnijholt/home-assistant-streamdeck-yaml-addon#32]
When I attempt to install, I get "Failed to install add-on:

The command '/bin/sh -c apk --no-cache add libusb=1.0.26-r0 libusb-dev=1.0.26-r0 hidapi-dev=0.12.0-r1 libffi-dev=3.4.4-r0 cairo-dev=1.17.6-r3 libxml2-dev=2.10.3-r1 libxslt-dev=1.1.37-r1 jpeg-dev=9e-r0 zlib-dev=1.2.13-r0 freetype-dev=2.12.1-r0 libpng-dev=1.6.38-r0 && apk add --no-cache --virtual build-deps gcc=12.2.1_git20220924-r4 python3-dev=3.10.11-r0 musl-dev=1.2.3-r4' returned a non-zero code: 2"

**Comment by basnijholt** [comment]
Are you on Alpine Linux?
And are you doing the manual install or is this from the Docker image?

**Comment by basnijholt** [comment]
Which system are you on? RPI4?

**Comment by basnijholt** [comment]
I will try installing it on a Raspberry Pi myself ASAP.

In the tests we're building for ARM v7 so I am not sure why it's failing for you.

**Comment by basnijholt** [comment]
Sorry, I still haven't gotten around to try it myself.

However, multiple folks seem to have been able to install this on a Supervised HA system, as reported in the main repo https://github.com/basnijholt/home-assistant-streamdeck-yaml.
