### ISSUE TITLE
Working  on HAOS

### ISSUE THREAD

**Issue by lonebaggie** [basnijholt/home-assistant-streamdeck-yaml-addon#36]
Add-on works fine in HA OS just setup the HA integration using long lived token

**Comment by basnijholt** [comment]
That’s great to hear. Thanks for reporting back. What device are you using?

**Comment by lonebaggie** [comment]
ODROID-N2+ (Home assistant blue) running 

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230411.1 - latest

Why does the  addon  need the host network ?

**Comment by basnijholt** [comment]
It might actually not need that. I think it is a leftover from debugging.
