### ISSUE TITLE
Remote Configuration

### ISSUE THREAD

**Issue by StonyManager** [basnijholt/home-assistant-streamdeck-yaml-addon#89]
If I understand correctly, I can keep my HA instance currently on an odroid N2+ and add an RPi4 to which I connect the stream deck. I'm looking for clarification on the RPi4 configuration/installation. I assume (which is dangerous) I need to install HA on the RPi4 first? At first, I was thinking it was just RPi4 running rasp o/s. But I'm not seeing how that would work. Thanks for the information.

**Comment by basnijholt** [comment]
Yes what you suggest would work. Then on that RPi4 you can run the Docker image or just install the Python library directly (which is how I use it).

**Comment by basnijholt** [comment]
Still need to remove this staleness bot...
